### ISSUE TITLE
Google chrome mobile pushing the last email item to the bottom. 

### ISSUE THREAD

**Issue by nousidis** [creativetimofficial/ct-blk-design-system-pro-react#6]
![mobile-chrome_error](https://user-images.githubusercontent.com/24785684/69855018-8a018980-1258-11ea-98b0-c93f35edd1ec.jpg)

I have tried going through the scss to edit some settings, but i cant seem to find the issue on why it is causing this. They also are not even. Just figured, I would post this here because you all know the product better than I do.

**Comment by einazare** [comment]
Hello there, @codelerk ,

Thank you for your interest in working with our products.
I would like to know on which page you have this issue, and also what device you are using?
And also, why did you ignore our rules of opening an issue: 
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/blk-design-system-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
It is important to use the above link so that we do not have to ask you questions like: `I would like to know on which page you have this issue, and also what device you are using?`.

For the moment, we are going to continue on this thread, but please next time follow our rules.

Will wait for your response.

Best,
Manu

**Comment by nousidis** [comment]
Hey you know what it's fine. Dont worry about it just delete it the
"issue." It said to post them on github or through an email and it seemed
like you all wanted it on github it's fine though. Dont worry about it.
